version: 2.1
orbs:
  cypress: cypress-io/cypress@1.3.0

jobs:
  release:
    executor: cypress/base-10
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run semantic-release

workflows:
  build:
    jobs:
      - cypress/install:
          build: 'npm run build'

      - cypress/run:
          name: '3 machines'
          requires:
            - cypress/install
          group: '3x-electron' # name this group
          start: 'npm start' # start server before running tests